### ISSUE TITLE
Create Documentation for NoOpAIProvider

### ISSUE THREAD

**Issue by thschue** [k8sgpt-ai/docs#13]
Checklist:
* [X] I've searched for similar issues and couldn't find anything matching
* [ ] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [X] No

## Describe the solution you'd like
In PR https://github.com/k8sgpt-ai/k8sgpt/pull/218, we introduced a NoOpAIProvider, which simply echoes the input of an AI request. We should write some documentation on how to use it 

## Benefits for the project and its users
Developers will know how to use the NoOpAIProvider

**Comment by rakshitgondwal** [comment]
I'd like to take this up!

**Comment by AnaisUrlichs** [comment]
Sorry, I just got to this, I assigned the issue to you @rakshitgondwal
