### ISSUE TITLE
feature: Help wanted documenting the k8sgpt-operator

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/docs#19]
Checklist:
* [ ] I've searched for similar issues and couldn't find anything matching
* [x ] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [ x] No

## Describe the solution you'd like

As we now have an operator it would be ideal to document the README on the docs site to help people get started.

https://github.com/k8sgpt-ai/k8sgpt-operator

## Benefits for the project and its users

Helps the community onboard easier and understand the operator and its purpose.

**Comment by rakshitgondwal** [comment]
Hey @AlexsJones! I'd like to work on this.

**Comment by AnaisUrlichs** [comment]
Hi @rakshitgondwal could you please add the content under "Reference/Operator" here is the snippet for mkdocs.yml
```
- Reference:
      - CLI:
          - Overview: reference/cli/index.md
          - Integration and Filter: reference/cli/filters.md
      - Operator:
          - Overview: reference/operator/index.md
      - Contributing Guidelines: reference/contributing/guidelines.md
      - Privacy: reference/privacy/index.md
```

Something like that. This is from my recent PR https://github.com/k8sgpt-ai/docs/pull/20
 Let me know if I can help with anything

**Comment by rakshitgondwal** [comment]
Sure! @AnaisUrlichs

**Comment by rakshitgondwal** [comment]
Hey @AlexsJones @AnaisUrlichs! Is this issue still viable after the merge of #24?

**Comment by AnaisUrlichs** [comment]
Hi @rakshitgondwal sorry for the late reply. I just added a few more details in this issue https://github.com/k8sgpt-ai/docs/pull/26/ to reference the configuration and
to make sure that the reference material is different from the getting-started guide.

It would be great if you could follow the docs, try it out and let us know if there is anything unclear in using the operator?

**Comment by rakshitgondwal** [comment]
Hey, @AnaisUrlichs!
- The step to install the helm chart is failing. cc- @AlexsJones @thschue 
![Screenshot from 2023-04-29 17-02-48](https://user-images.githubusercontent.com/98955085/235300344-654dbd6c-f2e9-4d2f-be9f-330ab3ee9d59.png)
- In the step of [deploying an OpenAI secret](https://github.com/k8sgpt-ai/docs/blob/main/docs/getting-started/in-cluster-operator.md#deploying-an-openai-secret), I think it would be a good idea to specify that how can a user set the global env variable. We can give an extra step here something like
```
export $OPENAI_TOKEN=<token>
```
or replacing $OPENAI_TOKEN with your token if he/she does not want to set the global env.

**Comment by AnaisUrlichs** [comment]
Hi @rakshitgondwal could you run 
```
helm repo update
```
and then try again to install the Helm Chart?
Also, which version of Helm are you using?
```
helm version
```

I will update the docs with your feedback thank you :)

**Comment by rakshitgondwal** [comment]
`helm repo update` did the work! Thank you. @AnaisUrlichs

**Comment by AnaisUrlichs** [comment]
I will close this issue for now as we have an overview with the values that can be changes and an installation guide for the operator.
