### ISSUE TITLE
feature: Document different AI backends

### ISSUE THREAD

**Issue by AnaisUrlichs** [k8sgpt-ai/docs#22]
Checklist:
* [x] I've searched for similar issues and couldn't find anything matching
* [ ] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [x] No

## Description 

It is now possible to use different AI backends e.g. https://github.com/k8sgpt-ai/k8sgpt/pull/309
This is not yet reflected in the documentation

**Comment by rakshitgondwal** [comment]
Hey, @AnaisUrlichs! I can work on this.

**Comment by AnaisUrlichs** [comment]
Amazing, assigned the issue to you :)
Please document the different backends under a separate file in the reference/cli section https://github.com/k8sgpt-ai/docs/tree/main/docs/reference/cli

**Comment by AnaisUrlichs** [comment]
Yes, 
> I was working on the documentation for the Azure AI backend, should I document NoOpAiProvider again?

Yes, please. Could you also please move the `providers` section from tutorials into reference? 

the tutorials should showcase detailed, end-to-end tutorials from installation to getting results etc. 
The providers section is more related to the docs, showing the different options.

**Comment by rakshitgondwal** [comment]
Hey @AnaisUrlichs, Can you please help me out here?

**Comment by AnaisUrlichs** [comment]
ahhh sorry @rakshitgondwal -- Maybe a combination of both
reference/providers/backend.md
I the providers apply to both the Kubernetes operator and the CLI -- thus, I would not put them under CLI. However, one file "backend.md" should be enough for now as there should not be THAT much to tell about each provider.
In the future, If I don't reply, you can also ping me on the Slack or go ahead and start a "WIP" (work in progress) PR 🙂

**Comment by rakshitgondwal** [comment]
> ahhh sorry @rakshitgondwal -- Maybe a combination of both reference/providers/backend.md I the providers apply to both the Kubernetes operator and the CLI -- thus, I would not put them under CLI. However, one file "backend.md" should be enough for now as there should not be THAT much to tell about each provider. In the future, If I don't reply, you can also ping me on the Slack or go ahead and start a "WIP" (work in progress) PR slightly_smiling_face

Thank you for the reply! Will raise a PR soon.
