### ISSUE TITLE
bug: Installtion steps on the website are not formatted correctly

### ISSUE THREAD

**Issue by harshit-mehtaa** [k8sgpt-ai/docs#30]
Checklist:

* [X] I've searched for similar issues and couldn't find anything matching
* [X] I've included steps to reproduce the bug.
* [ ] I've included the version of Kubernetes and k8sgpt.

### Subject of the issue

- Installtion steps on the [website](https://docs.k8sgpt.ai/getting-started/installation/) are not formatted correctly and look messed up

### Additional context / screenshots
![image](https://user-images.githubusercontent.com/17697790/232744588-7c4fa861-d65d-415b-9375-292413618660.png)

**Comment by AnaisUrlichs** [comment]
Hi @harshit-mehtaa I am not quite seeing where this is as this is the screenshot from the docs page that you linked above
<img width="725" alt="Screenshot 2023-05-03 at 15 04 19" src="https://user-images.githubusercontent.com/33576047/235939879-915a8229-7855-453a-81e4-2b2a2444b5ca.png">

Could you please provide the link?

**Comment by kaiwalyakoparkar** [comment]
@AnaisUrlichs in the earlier versions this was the issue, but doesn't seem to be anymore.
@harshit-mehtaa can you please re-confirm the issue?

I checked it on safari and chrome browser myself :)

**Comment by harshit-mehtaa** [comment]
Looks like documentation is updated so the issue is resolved
We are good to close the issue
