### ISSUE TITLE
[Feature]: K8sGPT Operator 

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/docs#33]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Problem Description

No Operator documentation

### Solution Description

We would like to have some documentation around setting up and running the operator.
Most of this can be lifted from the readme [here](https://github.com/k8sgpt-ai/k8sgpt-operator) but also enhanced and made more readable

### Benefits

This will lower the bar to entry for new starters

**Comment by AnaisUrlichs** [comment]
@AlexsJones we have the following two pages: 
https://docs.k8sgpt.ai/getting-started/in-cluster-operator/
https://docs.k8sgpt.ai/reference/operator/overview/

do you mean the architecture or the operator usage?

**Comment by AlexsJones** [comment]
I think this got merged in after I opened this title, these might cover what we need WDYT?
