### ISSUE TITLE
[Question]: Hyperlink text mismatch for Helm documentation

### ISSUE THREAD

**Issue by shijiadong2022** [k8sgpt-ai/docs#43]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [ ] K8sGPT Operator

### Steps to reproduce

https://github.com/k8sgpt-ai/docs/blob/main/docs/getting-started/in-cluster-operator.md 
You will also need to install helm v3. [See the Helm documentation for more information](https://helm.sh/docs/intro/install/).

Only Helm documentation should be the hyperlink text

### Expected behaviour

Only Helm documentation should be the hyperlink text

### Additional Information

I'd like to fix this issue

**Comment by shijiadong2022** [comment]
I'd like to work on it.

**Comment by SJ-Kumar** [comment]
I can work on this issue. Assign it to me.

**Comment by AnaisUrlichs** [comment]
When you see these small changes that you would like to make to the docs, feel free to go ahead and start a PR after creating an issue.

**Comment by rakshitgondwal** [comment]
Are you still working on this or do you need some help? @shijiadong2022

**Comment by AnaisUrlichs** [comment]
@rakshitgondwal I haven't seen a PR, feel free to update this one
