### ISSUE TITLE
ROADMAP: Documentation

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/docs#46]
In order to assist our users and provide better documentation then we wish to cover the following topics:
- Filters
- Caching
- Integations

**Comment by rakshitgondwal** [comment]
Would like to take up the filters part.

**Comment by AnaisUrlichs** [comment]
Hi @rakshitgondwal could you please create a separate issue and link to this milestone?

To provide more context:
All the documentation above is not hot to use these features -- we should already have documentation for it -- so not the command but focused on the design and processes implemented in the K8sGPT CLI.
So we want to add those topics to the explanation section in the documentation https://docs.k8sgpt.ai/explanation/

**Comment by rakshitgondwal** [comment]
> Hi @rakshitgondwal could you please create a separate issue and link to this milestone?
> 
> To provide more context: All the documentation above is not hot to use these features -- we should already have documentation for it -- so not the command but focused on the design and processes implemented in the K8sGPT CLI. So we want to add those topics to the explanation section in the documentation https://docs.k8sgpt.ai/explanation/

Sure! Will do.

**Comment by YashPimple** [comment]
Heyy @AlexsJones I would like to work on the Integrations part

**Comment by AlexsJones** [comment]
> Heyy @AlexsJones I would like to work on the Integrations part

Feel free to quote this issue in a new one!

**Comment by AnaisUrlichs** [comment]
https://docs.k8sgpt.ai/explanation/integrations/
