### ISSUE TITLE
Issues to fix

### ISSUE THREAD

**Issue by AnaisUrlichs** [k8sgpt-ai/docs#5]
[ ] Remove in docs edit button (we want the docs to link to the k8sgpt repo and the edit button will point to that)
[ ] This page needs extra spacing before bullet points https://docs.k8sgpt.ai/explanation/ to display them nicer

**Comment by rakshitgondwal** [comment]
Hey @AnaisUrlichs! I would like to work on this. Can you assign me this?

**Comment by thschue** [comment]
The first one with the edit button is already fixed (changed the edit URL in #9)

**Comment by AnaisUrlichs** [comment]
@rakshitgondwal I can assign another issues to you :)

**Comment by rakshitgondwal** [comment]
Sure! That would be great.

> @rakshitgondwal I can assign another issues to you :)
