### ISSUE TITLE
[Feature]: Add explanation for Integrations

### ISSUE THREAD

**Issue by YashPimple** [k8sgpt-ai/docs#56]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [ ] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

Yes

### Problem Description

Part #46

### Solution Description

Provide a proper explanation about Integrations used in the K8sGPT CLI.
Further, this should be added under the [explanation](https://docs.k8sgpt.ai/explanation/) section.

### Additional Information

I am working on it.

**Comment by rakshitgondwal** [comment]
Hey @YashPimple! 
Do consider these comments [1 ](https://github.com/k8sgpt-ai/docs/issues/46#issuecomment-1554497860)and [2 ](https://github.com/k8sgpt-ai/docs/pull/49#issuecomment-1577015834)while working on this :)

**Comment by YashPimple** [comment]
> 

Sure will do refer the comments [1](https://github.com/k8sgpt-ai/docs/issues/46#issuecomment-1554497860) and [2](https://github.com/k8sgpt-ai/docs/pull/49#issuecomment-1577015834)

**Comment by YashPimple** [comment]
> Hey @YashPimple! Do consider these comments [1 ](https://github.com/k8sgpt-ai/docs/issues/46#issuecomment-1554497860)and [2 ](https://github.com/k8sgpt-ai/docs/pull/49#issuecomment-1577015834)while working on this :)

Sure will do refer the comments [1](https://github.com/k8sgpt-ai/docs/issues/46#issuecomment-1554497860) and [2](https://github.com/k8sgpt-ai/docs/pull/49#issuecomment-1577015834)
