### ISSUE TITLE
[Bug]: update in-cluster-operator.md

### ISSUE THREAD

**Issue by Nitishupkr** [k8sgpt-ai/docs#59]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [X] K8sGPT Operator

### Steps to reproduce

1.https://github.com/k8sgpt-ai/docs/blob/f0f6406d56e7e94ded689d3cc67415991b87d731/docs/getting-started/in-cluster-operator.md?plain=1
![image](https://github.com/k8sgpt-ai/docs/assets/95420063/e261299e-eff3-4d2c-b74c-885839f385d1)
grammar mistake:  completed -> been completed
![Screenshot 2023-06-10 190321](https://github.com/k8sgpt-ai/docs/assets/95420063/0bd3c856-f534-4979-a788-13554d5bc22b)
add hyphen  : out-of-cluster

### Expected behaviour

grammar mistake:  completed -> been completed 
add hyphen  : out-of-cluster

### Additional Information

i  will rise a PR for this

**Comment by AnaisUrlichs** [comment]
Heya, could you please create a PR for any changes that you propose, thank you
