### ISSUE TITLE
Issue and PR templates

### ISSUE THREAD

**Issue by octonawish-akcodes** [k8sgpt-ai/docs#6]
It would be really nice to have an Issue and PR template for the repo because it will help to understand and format the issues and the changes proposed through a PR more accurately.

I can work on this, please assign it to me

**Comment by thschue** [comment]
I added this information to the https://github.com/k8sgpt-ai/.github repository

**Comment by thschue** [comment]
@AlexsJones: I think this issue can be closed ...
