### ISSUE TITLE
update filters.md

### ISSUE THREAD

**Issue by Nitishupkr** [k8sgpt-ai/docs#60]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

![k8gpt1](https://github.com/k8sgpt-ai/docs/assets/95420063/f832ac61-f19a-46b5-b001-e1e35885c991)
![k8gpt2](https://github.com/k8sgpt-ai/docs/assets/95420063/077ad3c3-67fa-4f4b-a07b-20d2d6902057)

### Solution Description

spelling mistake

### Benefits

Docs will look more accurate and good

### Additional Information

i will rise PR for this

**Comment by Nitishupkr** [comment]
@AnaisUrlichs  check it once

**Comment by YashPimple** [comment]
@Nitishupkr you can close this issue since it has been resolved
