### ISSUE TITLE
[Feature]: Add explanation for caching

### ISSUE THREAD

**Issue by YashPimple** [k8sgpt-ai/docs#72]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

Yes

### Problem Description

Part https://github.com/k8sgpt-ai/docs/issues/46

### Solution Description

Provide a proper explanation about caching used in the K8sGPT CLI.
Further, this should be added under the [explanation](https://docs.k8sgpt.ai/explanation/) section.

### Additional Information

I am working on it.

**Comment by YashPimple** [comment]
@AlexsJones would appreciate your review for the above PR

**Comment by AlexsJones** [comment]
> @AlexsJones would appreciate your review for the above PR

Thanks, reviewed and merged!
