### ISSUE TITLE
schema.v1.ServerService instead of schema.v1.Server

### ISSUE THREAD

**Issue by jkleinlercher** [k8sgpt-ai/docs#74]
instead of schema.v1.Server the correct resource is schema.v1.ServerService

e.g.:
https://github.com/k8sgpt-ai/docs/blob/ce9e48faa997ab2cc6f1d173ac8e0c67f15037d9/docs/reference/cli/serve-mode.md?plain=1#L33

**Comment by AnaisUrlichs** [comment]
This got fixed
